# Dockerfile.airflow
FROM apache/airflow:2.9.1

# Installer Java pour PySpark
USER root
RUN apt-get update && apt-get install -y default-jdk && apt-get clean

USER airflow
# Installation PySpark
RUN pip install --no-cache-dir pyspark pandas